# Generated by Django 2.0.2 on 2019-07-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifycode',
            name='mobile',
        ),
        migrations.AddField(
            model_name='verifycode',
            name='email',
            field=models.CharField(default=2, max_length=100, verbose_name='邮箱地址'),
            preserve_default=False,
        ),
    ]
