# Generated by Django 2.0.2 on 2019-07-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190724_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='邮箱地址'),
        ),
    ]
